### ISSUE TITLE
Send variable within quotes

### ISSUE THREAD

**Issue by quankaroo** [timestored/pulse-client#113]
Hi,
I'm trying to send a query with quotes. e.g.
``.equities.getTradeData "select sym,bid,ask from quotes where sym=`$\"{NAME}\"" .``
But it seems to get confused. AS hardcoding does work. 

Please advise.

**Comment by ryanhamilton** [comment]
Fixed in 1.34.

Added variable formatters https://www.timestored.com/pulse/help/variables#varformatters


![image](https://github.com/timestored/pulse-client/assets/7273208/84738459-f824-4da7-8949-3a81011c6667)
