### ISSUE TITLE
Every 10s and 1Min Data refresh not present - As sqlDashboard Had

### ISSUE THREAD

**Issue by BraveCee** [timestored/pulse-client#13]
user-pn
Would really appreciate having at least the same refresh's that were present on sqlDashboard, specificly the 10s and 1min. I like the new longer refreshes too. Even better would be customisable if poss.

**Comment by ryanhamilton** [comment]
THanks for raising this issue. I will investigate the effort to allow fully custom times and get back to you this week.

**Comment by ryanhamilton** [comment]
Adding 10s/1 min. 

![image](https://user-images.githubusercontent.com/7273208/206012967-f3cf63fc-b4df-4e52-a811-ce1d9fbab942.png)

Investigated allowing freer form entry but decided against for now, as:
a) It's costly to implement. People probably wouldn't be content entering seconds for very large values, 
b) I'm not sure we want to encourage even longer refreshes.

**Comment by ryanhamilton** [comment]
Latest version 0.11.5 released.
Download: https://www.timestored.com/pulse/download
Live Demo: http://pulse.timestored.com/dash
Closing as fixed. Please reopen if you find a problem.

**Comment by ryanhamilton** [comment]
Reopening as more users have requested customizable.

**Comment by ryanhamilton** [comment]
Added 250ms 
![image](https://user-images.githubusercontent.com/7273208/210149182-3a3db1bd-ecbc-4cc7-b8bb-799e71fe7232.png)
