### ISSUE TITLE
While using the FormEditor with multiple labels - DataSource SQL Query not refreshed when clicking Label.

### ISSUE THREAD

**Issue by BraveCee** [timestored/pulse-client#14]
When in FormEditor with multiple Labels, on clicking a different Label, the CompenentEditor does not display the coresponding DataSource SQL query unless you press List and then SQL.

**Comment by ryanhamilton** [comment]
You are correct, the next big milestone we need to improve are User Forms. 
I've created the milestone and assigned this issue to it. 

You can expect:
1. 2 Bundled form demos
2. While doing the demos, we will fix any obvious bugs.
3. Your particular bug will likely be fixed as part of that, if not I will look at it individually within 4 weeks.

If you have any other form suggestions in general please leave them all in this issue.

**Comment by BraveCee** [comment]
I Have not fully thought about this as yet, but.
On initial creation in Pulse of a Form I had in sqlDashboard, I have observed that when using 
date(DATE) or
time(DATE) 
within a query, that the time Zone is appended, this did not occur in sqlDashboard.

I realise that indirectly this is correct, but it is making the move to Pulse more involved than initially perceived.

My initial question to this is, other than utilising formatting within the query, does Pulse offer any methods to supress or control the time Zone addition.

**Comment by ryanhamilton** [comment]
Not yet. So far your only control is on the SQL side.

Would you consider the ability to run javascript on parameters before sending to SQL a good solution?

e.g. Where we have ``((date))`` or ``{date}`` 
You could do ``((date.substring(8)))`` or ``date.split('Z')[0]``

**Comment by BraveCee** [comment]
Good idea, this would sound like the ideal solution if easily achievable. Unless this is already an option without my awareness.

**Comment by BraveCee** [comment]
This is a bug I think, drove me crazy for a while (I just wish I had started vertically and NOT horizontally :) ).
In Form Editor with Multiple Labels (I have 9 as type dropdown and 2 radio buttons), but I believe the issue is screen space related due to the Form Editor loading on the right-hand side when in design mode.

The Issue is when they are displayed vertically all are selectable whether in design mode or NOT, however, when displayed horizontally, all on the right-hand 3rd ish of the screen are NOT selectable when design mode is switched off.

**Comment by ryanhamilton** [comment]
Ah sorry about that.  That bug slipped in last week. I've found the problem and fixed it.  I'll get a release out today.

**Comment by ryanhamilton** [comment]
We had been using _ as a separator between multiple items in the URL.
I'm going to make a breaking change to use ~ instead. 
That will cause dashboards with checkboxes saved to lose record of some of those checkboxes.
I feel the benefit outweighs the temporary pain.
The benefits are:
-  that ~ is very uncommon so URLs will be more readable
- It means less chance of people ever encountering bugs in future

**Comment by ryanhamilton** [comment]
Fix is released. 0.11.6
