### ISSUE TITLE
Using the Light/Dark Themes. Panel Names difficult to read when set to half Moon

### ISSUE THREAD

**Issue by BraveCee** [timestored/pulse-client#15]
When using the Half Moon setting at top right, left of admin. All Panel names are very difficult to read (grey writing on light blue). Is there a method to change this.

**Comment by ryanhamilton** [comment]
Image to demonstrate the problem:
![image](https://user-images.githubusercontent.com/7273208/205936571-5696df59-6aef-4acc-b9b3-deecd82590c8.png)

We actually tried to improve this color before but I think we had a problem agreeing a replacement.
I'll get back to you this week.
If you have any other light-theme issues, please leave them here and I will resolve at the same time.

**Comment by BraveCee** [comment]
Yes, you have confirmed the correct area that is difficult to read.  
As a little more personal feedback. My opinion is....
 Since pressing the half moon almost achieves a look and feel of sqlDashboard apart from this area, with that in mind I would have thought using the sqlDashboard Panel name colour scheme would be an obvious choice, been black on light blue and NOT grey on light blue.

**Comment by BraveCee** [comment]
Yes, That looks great.

**Comment by ryanhamilton** [comment]
Excellent.
It will be released to website for download by Friday 2PM UK at the latest.
I would like to resolve a few of your other issues first and then there's some manual testing before every release.

**Comment by BraveCee** [comment]
FYI, I have just noticed that if the half moon has been selected and the dashboard saved, On Going back to available dashboards and re-selecting the one just saved, it appears to have saved it. But sadly, once the session has ended and the pulse background task closed too.

A Full Re-Launch of pulse and re-selected said dashboard it defaults back to light and NOT as half moon as was saved.

**Comment by ryanhamilton** [comment]
The theme setting is by user not by chart.
Unless the author starts overriding the specific chart colors.
This seemed the best way to give most users what they want. 
Does that explain what you are seeing?

**Comment by BraveCee** [comment]
Ahh, I think this is likely to explain the behaviour, if I am correct in thinking that the user theme settings are currently related to cookies ?. After your response it occurred to me to try NOT delete browser cookies on exit in edge, this seems to address my initial observation.

Not fully following your statement ref 'Unless the author starts overriding the specific chart colors.'. Does this interact with the half moon / light feature selection.

**Comment by ryanhamilton** [comment]
>> that the user theme settings are currently related to cookies ?.
Yes.

>>'Unless the author starts overriding the specific chart colors.'. Does this interact with the half moon / light feature selection.
The Moon controls the general theme for the logged in user. Default charts will change based on theme.
Chart authors can set specific background colors. Once they are set they will override the default theme. As shown below.

![image](https://user-images.githubusercontent.com/7273208/206236321-b910c825-5713-4238-98a9-0979353a2506.png)

![image](https://user-images.githubusercontent.com/7273208/206236391-db39f25e-600f-4bdc-982e-fb608f808e86.png)
