### ISSUE TITLE
After Installing v0.11.5, 3 of my recently created dashboards from v0.11.4 can no longer be modified

### ISSUE THREAD

**Issue by BraveCee** [timestored/pulse-client#16]
I had created 5 dashboards in total with v0.11.4. On installing v0.11.5 only 2 of them can be modified leaving 3 un-modifiable. On attempting to save, the following is reported

Request Failed with status code 500
Save Failed
Taking Screenshot.

When I tried downgrading to v0.11.4, all dashboards where modifiable again. On then returning back to v0.11.5 the same 3 dashboards where once again un-modifiable.

![pulse_0115_SaveIssue](https://user-images.githubusercontent.com/119947521/206446098-ab8ccab6-8581-4b2d-8374-9f422875f259.jpg)

**Comment by ryanhamilton** [comment]
That's very serious. 
Sorry that happened. We do test database upgrades as part of our test cycle.

Would it be possible to forward your database file to me?
ryan@timestored.com
If not, that's fine, I think I can recreate it myself.

For future I'm also going to:
1. Increase the recovery code, to recover from bad scenarios
2. Expose more tooling to allow independent recovery in the event of a problem

**Comment by BraveCee** [comment]
I don't mind doing so, since All my testing has been conducted on a test server and not a live one. Is it the dashboard file you require or the pulsedb.mv ?.

**Comment by BraveCee** [comment]
Just sent, let me know if you don't receive or require anything further from me regarding this issue.
